version: '3.8'

services:
  streamlit:
    build: 
      context: ./app 
    container_name: Data_stack_app
    ports:
      - "8502:8502"

  elasticsearch:
    build:
      context: ./app
    container_name: Data_stack_app
    ports:
      - "9200:9200"